# fly.toml app configuration file generated for liminal-umbrella on 2024-02-23T21:57:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liminal-umbrella'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  NODE_ENV = "production"

[[vm]]
  size = 'shared-cpu-1x'
