# fly.toml app configuration file generated for liminal-umbrella on 2024-02-23T21:57:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liminal-umbrella'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "2s"
  path = "/health"
  protocol = "http"

[metrics]
  port = 8080
  path = "/metrics"

[env]
  NODE_ENV = "development"
  DATABASE_NAME = "/data/database.sqlite"
  DISCORD_GUILD_ID = "1205971443523788840"

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "liminal_umbrella"
  destination = "/data"
